# Generated by Django 5.1.7 on 2026-03-14 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='item',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='item',
            name='features',
            field=models.JSONField(blank=True, default=list, verbose_name='核心特征'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=120, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='item',
            name='origin',
            field=models.CharField(blank=True, max_length=120, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pairing',
            field=models.TextField(blank=True, verbose_name='适配建议'),
        ),
        migrations.AlterField(
            model_name='item',
            name='scene',
            field=models.TextField(blank=True, verbose_name='适用场景'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=140, verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.subcategory', verbose_name='子类'),
        ),
        migrations.AlterField(
            model_name='item',
            name='summary',
            field=models.TextField(blank=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='purchaselink',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='purchaselink',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_links', to='catalog.item', verbose_name='条目'),
        ),
        migrations.AlterField(
            model_name='purchaselink',
            name='label',
            field=models.CharField(max_length=80, verbose_name='链接名称'),
        ),
        migrations.AlterField(
            model_name='purchaselink',
            name='platform',
            field=models.CharField(blank=True, max_length=80, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='purchaselink',
            name='url',
            field=models.URLField(max_length=500, verbose_name='链接地址'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category', verbose_name='主类'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=120, verbose_name='标识'),
        ),
    ]
