# Generated by Django 5.1.7 on 2026-03-14 01:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TastingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='品茗时间')),
                ('water_temp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='水温（℃）')),
                ('steep_time', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='浸泡时长（秒）')),
                ('tea_amount', models.CharField(blank=True, max_length=40, verbose_name='用茶量')),
                ('water_type', models.CharField(blank=True, max_length=80, verbose_name='用水')),
                ('aroma', models.TextField(blank=True, verbose_name='香气')),
                ('taste', models.TextField(blank=True, verbose_name='口感')),
                ('color', models.CharField(blank=True, max_length=60, verbose_name='汤色')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='评分')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('weather', models.CharField(blank=True, max_length=60, verbose_name='天气')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='地点')),
                ('participants', models.TextField(blank=True, verbose_name='参与人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tea_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasting_records', to='catalog.item', verbose_name='茶叶条目')),
            ],
            options={
                'verbose_name': '品茗记录',
                'verbose_name_plural': '品茗记录',
                'ordering': ['-date'],
            },
        ),
    ]
