# Generated by Django 5.1.7 on 2026-03-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_description_and_more'),
        ('tasting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tastingrecord',
            name='tea_item',
        ),
        migrations.AddField(
            model_name='tastingrecord',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='tasting_records', to='catalog.item', verbose_name='品茗条目'),
        ),
    ]
